### ISSUE TITLE
There is a stray black line floating in the footer of the site (improperly hidden banner container)

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-org#1755]
<img width="834" alt="Screenshot 2020-03-31 10 24 40" src="https://user-images.githubusercontent.com/811963/78037831-0ce73d80-733a-11ea-8e9b-fb86f85467ea.png">

<img width="818" alt="Screenshot 2020-03-31 10 24 51" src="https://user-images.githubusercontent.com/811963/78037846-11135b00-733a-11ea-80b3-6b2feb044675.png">

**Comment by evwilkin** [comment]
Resolved in #1733

**Comment by mturley** [comment]
Ah, thanks @evwilkin! It looks like that change was released 11 days ago, but I still see it on the production website today (I cleared my cache, etc). Do you know what our process/schedule is for updating the site?

**Comment by evwilkin** [comment]
Thanks for the call-out @mturley - we're in the process of testing the new release currently, and should see these changes reflected on the site with the new release in the next day or two!

**Comment by mturley** [comment]
Awesome, thanks! Sorry for the churn, I wasn't in the loop.
